### ISSUE TITLE
Console/terminal doesn't display the privileges status of the newly registered users

### ISSUE THREAD

**Issue by zainurrehman** [haiduowad/Group2SecureCodingDojo#3]
For the registered users, console/terminal shows the proper privileges log
For newly registered users, it doesn't.

**Comment by haiduowad** [comment]
Fixed. The console.log comment has been added in auth.js when a new user is registered.

**Comment by haiduowad** [comment]
Fixed. The console.log comment has been added in auth.js when a new user is registered.
